[book]
title = "AeroFTP Documentation"
authors = ["AXP Development"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/axpnet/aeroftp"
edit-url-template = "https://github.com/axpnet/docs.aeroftp.app/edit/main/src/{path}"
site-url = "https://docs.aeroftp.app/"
additional-css = ["src/custom.css"]
additional-js = ["src/custom.js"]
